import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Form from '../comps/Form'
import Link from "next/link";
import Heading from '../comps/Heading';
import { useState } from 'react';
import Recipes from './recipes';

// Import the functions you need from the SDKs you need
import { initializeApp } from "firebase/app";
import { getAnalytics } from "firebase/analytics";
// TODO: Add SDKs for Firebase products that you want to use
// https://firebase.google.com/docs/web/setup#available-libraries

// Your web app's Firebase configuration
// For Firebase JS SDK v7.20.0 and later, measurementId is optional
const firebaseConfig = {
  apiKey: "AIzaSyC8LXWNV5OhE7HbklA4vq8zgXzM_feze3M",
  authDomain: "mealease-7bf7f.firebaseapp.com",
  databaseURL: "https://mealease-7bf7f-default-rtdb.firebaseio.com",
  projectId: "mealease-7bf7f",
  storageBucket: "mealease-7bf7f.appspot.com",
  messagingSenderId: "792708407205",
  appId: "1:792708407205:web:ffb058b5badb6eee1c124c",
  measurementId: "G-3D6BSF0991"
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);
const analytics = getAnalytics(app);

export default function Home() {
    const [email,setEmail] = useState(" ")

    function handleChange(e) {
      const newval = e.target.value;
      setEmail({
        ...email, newval
      });
    }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex justify-center flex-col items-center">
        <Heading heading="FitMeal" info="spend your time eating not deciding" />
        <div className="flex justify-center flex-col items-center">
          <Form
            value={email.value}
            label="Pass"
            placeholder="Enter Email"
            onChange={handleChange}
          />
          <Form
            value={email.value}
            label="Pass"
            placeholder="Enter Email"
            onChange={handleChange}
          />

          <Link href="/ingredients">
            <button className="rounded-md bg-indigo-500 w-1/2 ">
              <a>Sign In</a>
            </button>
          </Link>

          <Link href="/recipes">
            <button className="rounded-md bg-indigo-500 w-1/2 ">
              <a>Recipes</a>
            </button>
          </Link>
        </div>
      </main>

      {/*       <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
}
