import Heading from "../comps/Heading";
import Form from "../comps/Form";
import Head from "next/head";
import Navbar from "../comps/Navbar";
import { useState } from "react";

export default function Recipes() {
  <div className >
    <Head>
      <title>Recipes</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Navbar page="/" />
  </div>;
}
