import Head from "next/head";
import styles from "../styles/Home.module.scss";
import Heading from "../comps/Heading";
import Register from "../auth/Register";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sign Up</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.mainContent}>
        <Heading
          heading="Meal-Ease"
          info="spend your time eating not deciding"
        />
        <div className={styles.auth}>
          <Register />
          <p>
            Already have an account?{" "}
            <a
              style={{
                textDecoration: "underline",
                cursor: "pointer",
              }}
              onClick={() => {
                router.push("/");
              }}
            >
              {" "}
              Sign in.
            </a>
          </p>
        </div>
      </main>
    </div>
  );
}
